stages:

  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
      - src/stages/data_load.py
    params:
      - base
      - data_load
      - data
    outs:
      - data/processed/X.npy
      - reports/original_shape.json

  train:
    cmd: python src/stages/train_model.py --config=params.yaml
    deps:
      - src/stages/train_model.py
      - data/processed/X.npy
      - src/train/train.py
    params:
      - base
      - train
    outs:
      - models/model.joblib
      - reports/metrics.json

  evaluate:
    cmd: python src/stages/evaluate.py --config=params.yaml
    deps:
      - models/model.joblib
      - data/processed/X.npy
      - reports/original_shape.json
    params:
      - base
      - reports
    outs:
      - reports/result.jpg
